spring.application.name=validation
spring.application.name=project1
# ===============================
# = DATA SOURCE CONFIGURATION
# ===============================

spring.datasource.url=jdbc:mysql://localhost:3306/logg
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# ===============================
# = JPA / HIBERNATE CONFIG
# ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect


# ===============================
# = SERVER CONFIG (Optional)
# ===============================

server.port=8080